name: Kellerman.Biz Development
favicon: null
layout_spectrum: 0.6960934095550328
typography_spectrum: 0.5420281372498721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8608729252591729
  lightness: 0.641725066350773
  saturation: 0.5139354227576405
  rhythmicContrast: 0.3574319672770798
purpose: []
